"""
ESPN team ID and abbreviation mappings for NCAA D1 men's basketball.

Maps Odds API team names (format: "School Name Mascot") to:
- ESPN numeric team IDs (used in ESPN CDN logo URLs)
- Short abbreviations for display

ESPN logo URL pattern:
    https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/{id}.png&w=40&h=40
"""

from __future__ import annotations


# ---------------------------------------------------------------------------
# Odds API team name -> ESPN numeric team ID
#
# Sources: ESPN public API (/apis/site/v2/sports/basketball/mens-college-basketball/teams)
# and manual verification of ESPN team pages.
#
# NOTE: Some Odds API names have multiple variants (e.g. "Mississippi Rebels"
# vs "Ole Miss Rebels"). All known variants are included for robustness.
# ---------------------------------------------------------------------------
ODDS_API_TO_ESPN_ID: dict[str, int] = {
    # --- A ---
    "Abilene Christian Wildcats": 2000,
    "Air Force Falcons": 2005,
    "Akron Zips": 2006,
    "Alabama Crimson Tide": 333,
    "Alabama A&M Bulldogs": 2010,
    "Alabama State Hornets": 2011,
    "Albany Great Danes": 399,
    "Alcorn State Braves": 2016,
    "American Eagles": 44,
    "Appalachian State Mountaineers": 2026,
    "Arizona Wildcats": 12,
    "Arizona State Sun Devils": 9,
    "Arizona St Sun Devils": 9,
    "Arkansas Razorbacks": 8,
    "Arkansas State Red Wolves": 2032,
    "Arkansas-Little Rock Trojans": 2031,
    "Arkansas-Pine Bluff Golden Lions": 2029,
    "Army Black Knights": 349,
    "Auburn Tigers": 2,
    "Austin Peay Governors": 2046,
    # --- B ---
    "Ball State Cardinals": 2050,
    "Baylor Bears": 239,
    "Bellarmine Knights": 91,
    "Belmont Bruins": 2057,
    "Bethune-Cookman Wildcats": 2065,
    "Binghamton Bearcats": 2066,
    "Boise State Broncos": 68,
    "Boston College Eagles": 103,
    "Boston University Terriers": 104,
    "Bowling Green Falcons": 189,
    "Bradley Braves": 71,
    "Brown Bears": 225,
    "Bryant Bulldogs": 2803,
    "Bucknell Bison": 2083,
    "Buffalo Bulls": 2084,
    "Butler Bulldogs": 2086,
    "BYU Cougars": 252,
    # --- C ---
    "Cal Poly Mustangs": 13,
    "Cal State-Bakersfield Roadrunners": 2934,
    "Cal State-Fullerton Titans": 2239,
    "Cal State-Northridge Matadors": 2463,
    "California Golden Bears": 25,
    "California Baptist Lancers": 2856,
    "Campbell Fighting Camels": 2097,
    "Canisius Golden Griffins": 2099,
    "Central Arkansas Bears": 2110,
    "Central Connecticut State Blue Devils": 2115,
    "Central Florida Knights": 2116,
    "Central Michigan Chippewas": 2117,
    "Charleston Cougars": 232,
    "Charleston Southern Buccaneers": 2127,
    "Charlotte 49ers": 2429,
    "Chattanooga Mocs": 236,
    "Chicago State Cougars": 2130,
    "Cincinnati Bearcats": 2132,
    "Clemson Tigers": 228,
    "Cleveland State Vikings": 325,
    "Coastal Carolina Chanticleers": 324,
    "Colgate Raiders": 2142,
    "Colorado Buffaloes": 38,
    "Colorado State Rams": 36,
    "Columbia Lions": 171,
    "Connecticut Huskies": 41,
    "Coppin State Eagles": 2154,
    "Cornell Big Red": 172,
    "Creighton Bluejays": 156,
    # --- D ---
    "Dartmouth Big Green": 159,
    "Davidson Wildcats": 2166,
    "Dayton Flyers": 2168,
    "DePaul Blue Demons": 305,
    "Delaware Fightin Blue Hens": 48,
    "Delaware State Hornets": 2169,
    "Denver Pioneers": 2172,
    "Detroit Mercy Titans": 2174,
    "Drake Bulldogs": 2181,
    "Drexel Dragons": 2182,
    "Duke Blue Devils": 150,
    "Duquesne Dukes": 2184,
    # --- E ---
    "East Carolina Pirates": 151,
    "East Texas A&M Lions": 2249,
    "Eastern Illinois Panthers": 2197,
    "Eastern Kentucky Colonels": 2198,
    "Eastern Michigan Eagles": 2199,
    "Eastern Washington Eagles": 331,
    "Elon Phoenix": 2210,
    "Evansville Purple Aces": 339,
    # --- F ---
    "Fairfield Stags": 2217,
    "Fairleigh Dickinson Knights": 2218,
    "FIU Panthers": 2229,
    "Florida Gators": 57,
    "Florida A&M Rattlers": 50,
    "Florida Atlantic Owls": 2226,
    "Florida Gulf Coast Eagles": 526,
    "Florida International Golden Panthers": 2229,
    "Florida State Seminoles": 52,
    "Florida St Seminoles": 52,
    "Fordham Rams": 2230,
    "Fresno State Bulldogs": 278,
    "Furman Paladins": 231,
    # --- G ---
    "Gardner-Webb Runnin Bulldogs": 2241,
    "George Mason Patriots": 2244,
    "George Washington Colonials": 45,
    "Georgetown Hoyas": 46,
    "Georgia Bulldogs": 61,
    "Georgia Southern Eagles": 290,
    "Georgia State Panthers": 2247,
    "Georgia Tech Yellow Jackets": 59,
    "Gonzaga Bulldogs": 2250,
    "Grambling Tigers": 2755,
    "Grand Canyon Antelopes": 2253,
    "Green Bay Phoenix": 2739,
    # --- H ---
    "Hampton Pirates": 2261,
    "Hartford Hawks": 42,
    "Harvard Crimson": 108,
    "Hawaii Rainbow Warriors": 62,
    "Hawai'i Rainbow Warriors": 62,
    "High Point Panthers": 2272,
    "Hofstra Pride": 2275,
    "Holy Cross Crusaders": 107,
    "Houston Cougars": 248,
    "Houston Christian Huskies": 2277,
    "Howard Bison": 47,
    # --- I ---
    "Idaho Vandals": 70,
    "Idaho State Bengals": 304,
    "Illinois Fighting Illini": 356,
    "Illinois State Redbirds": 2287,
    "Illinois-Chicago Flames": 82,
    "Incarnate Word Cardinals": 2916,
    "Indiana Hoosiers": 84,
    "Indiana State Sycamores": 282,
    "Indiana-Purdue-Indianapolis Jaguars": 85,
    "Iona Gaels": 314,
    "Iowa Hawkeyes": 2294,
    "Iowa State Cyclones": 66,
    "IUPUI Jaguars": 85,
    # --- J ---
    "Jackson State Tigers": 2296,
    "Jacksonville Dolphins": 294,
    "Jacksonville State Gamecocks": 55,
    "James Madison Dukes": 256,
    # --- K ---
    "Kansas Jayhawks": 2305,
    "Kansas City Roos": 140,
    "Kansas State Wildcats": 2306,
    "Kennesaw State Owls": 338,
    "Kent State Golden Flashes": 2309,
    "Kentucky Wildcats": 96,
    # --- L ---
    "LIU Sharks": 2344,
    "La Salle Explorers": 2325,
    "Lafayette Leopards": 322,
    "Lamar Cardinals": 2320,
    "Le Moyne Dolphins": 2769,
    "Lehigh Mountain Hawks": 2329,
    "Liberty Flames": 2335,
    "Lindenwood Lions": 2815,
    "Lipscomb Bisons": 288,
    "Little Rock Trojans": 2031,
    "Long Beach State Beach": 299,
    "Long Island University Sharks": 2344,
    "Louisiana Ragin Cajuns": 309,
    "Louisiana-Lafayette Ragin Cajuns": 309,
    "Louisiana-Monroe Warhawks": 2433,
    "Louisiana Tech Bulldogs": 2348,
    "Louisville Cardinals": 97,
    "Loyola Chicago Ramblers": 2350,
    "Loyola (IL) Ramblers": 2350,
    "Loyola (MD) Greyhounds": 2352,
    "Loyola Marymount Lions": 2351,
    "LSU Tigers": 99,
    # --- M ---
    "Maine Black Bears": 311,
    "Manhattan Jaspers": 2363,
    "Marist Red Foxes": 2368,
    "Marquette Golden Eagles": 269,
    "Marshall Thundering Herd": 276,
    "Maryland Terrapins": 120,
    "Maryland-Eastern Shore Hawks": 2379,
    "Massachusetts Minutemen": 113,
    "McNeese Cowboys": 2377,
    "Memphis Tigers": 235,
    "Mercer Bears": 2382,
    "Merrimack Warriors": 2771,
    "Miami Hurricanes": 2390,
    "Miami (FL) Hurricanes": 2390,
    "Miami (OH) RedHawks": 193,
    "Michigan Wolverines": 130,
    "Michigan State Spartans": 127,
    "Middle Tennessee Blue Raiders": 2393,
    "Milwaukee Panthers": 270,
    "Minnesota Golden Gophers": 135,
    "Mississippi Rebels": 145,
    "Ole Miss Rebels": 145,
    "Mississippi State Bulldogs": 344,
    "Mississippi Valley State Delta Devils": 2400,
    "Missouri Tigers": 142,
    "Missouri State Bears": 2623,
    "Monmouth Hawks": 2405,
    "Montana Grizzlies": 149,
    "Montana State Bobcats": 147,
    "Morehead State Eagles": 2413,
    "Morehead St Eagles": 2413,
    "Morgan State Bears": 2415,
    "Mount St. Mary's Mountaineers": 116,
    "Murray State Racers": 93,
    # --- N ---
    "Navy Midshipmen": 2426,
    "NC State Wolfpack": 152,
    "N.C. State Wolfpack": 152,
    "Nebraska Cornhuskers": 158,
    "Nebraska-Omaha Mavericks": 2437,
    "Omaha Mavericks": 2437,
    "Nevada Wolf Pack": 2440,
    "New Hampshire Wildcats": 160,
    "New Mexico Lobos": 167,
    "New Mexico State Aggies": 166,
    "New Orleans Privateers": 2443,
    "Niagara Purple Eagles": 315,
    "Nicholls State Colonels": 2447,
    "NJIT Highlanders": 2885,
    "Norfolk State Spartans": 2450,
    "North Alabama Lions": 2453,
    "North Carolina Tar Heels": 153,
    "North Carolina A&T Aggies": 2448,
    "North Carolina Central Eagles": 2428,
    "North Carolina State Wolfpack": 152,
    "North Dakota Fighting Hawks": 155,
    "North Dakota State Bison": 2449,
    "North Florida Ospreys": 2454,
    "North Texas Mean Green": 249,
    "Northeastern Huskies": 111,
    "Northern Arizona Lumberjacks": 2464,
    "Northern Colorado Bears": 2458,
    "Northern Illinois Huskies": 2459,
    "Northern Iowa Panthers": 2460,
    "Northern Kentucky Norse": 94,
    "Northwestern Wildcats": 77,
    "Northwestern State Demons": 2466,
    "Notre Dame Fighting Irish": 87,
    # --- O ---
    "Oakland Golden Grizzlies": 2473,
    "Ohio Bobcats": 195,
    "Ohio State Buckeyes": 194,
    "Oklahoma Sooners": 201,
    "Oklahoma State Cowboys": 197,
    "Oklahoma St Cowboys": 197,
    "Old Dominion Monarchs": 295,
    "Oral Roberts Golden Eagles": 198,
    "Oregon Ducks": 2483,
    "Oregon State Beavers": 204,
    # --- P ---
    "Pacific Tigers": 279,
    "Penn Quakers": 219,
    "Penn State Nittany Lions": 213,
    "Pepperdine Waves": 2492,
    "Pittsburgh Panthers": 221,
    "Portland Pilots": 2501,
    "Portland State Vikings": 2502,
    "Prairie View A&M Panthers": 2504,
    "Presbyterian Blue Hose": 2506,
    "Princeton Tigers": 163,
    "Providence Friars": 2507,
    "Purdue Boilermakers": 2509,
    "Purdue Fort Wayne Mastodons": 2870,
    # --- Q ---
    "Queens Royals": 2801,
    "Queens University Royals": 2801,
    "Quinnipiac Bobcats": 2514,
    # --- R ---
    "Radford Highlanders": 2515,
    "Rhode Island Rams": 227,
    "Rice Owls": 242,
    "Richmond Spiders": 257,
    "Rider Broncs": 2520,
    "Robert Morris Colonials": 2523,
    "Rutgers Scarlet Knights": 164,
    # --- S ---
    "Sacramento State Hornets": 16,
    "Sacred Heart Pioneers": 2529,
    "Saint Francis Red Flash": 2598,
    "Saint Joseph's Hawks": 2603,
    "Saint Louis Billikens": 139,
    "Saint Mary's Gaels": 2608,
    "Saint Peter's Peacocks": 2612,
    "Sam Houston Bearkats": 2534,
    "Sam Houston State Bearkats": 2534,
    "Samford Bulldogs": 2535,
    "San Diego Toreros": 301,
    "San Diego State Aztecs": 21,
    "San Diego St Aztecs": 21,
    "San Francisco Dons": 2539,
    "San Jose State Spartans": 23,
    "Santa Clara Broncos": 2541,
    "Seattle Redhawks": 2547,
    "Seton Hall Pirates": 2550,
    "Siena Saints": 2561,
    "SIU-Edwardsville Cougars": 2565,
    "SMU Mustangs": 2567,
    "South Alabama Jaguars": 6,
    "South Carolina Gamecocks": 2579,
    "South Carolina State Bulldogs": 2569,
    "South Carolina-Upstate Spartans": 2908,
    "USC-Upstate Spartans": 2908,
    "South Dakota Coyotes": 233,
    "South Dakota State Jackrabbits": 2571,
    "South Florida Bulls": 58,
    "Southeast Missouri State Redhawks": 2546,
    "SE Missouri St Redhawks": 2546,
    "Southeastern Louisiana Lions": 2545,
    "Southern Jaguars": 2582,
    "Southern Illinois Salukis": 79,
    "Southern Miss Golden Eagles": 2572,
    "Southern Mississippi Golden Eagles": 2572,
    "Southern University Jaguars": 2582,
    "Southern Utah Thunderbirds": 253,
    "St. Bonaventure Bonnies": 179,
    "St. John's Red Storm": 2599,
    "St. Thomas Tommies": 2900,
    "Stanford Cardinal": 24,
    "Stephen F. Austin Lumberjacks": 2617,
    "Stetson Hatters": 56,
    "Stonehill Skyhawks": 2773,
    "Stony Brook Seawolves": 2619,
    "Syracuse Orange": 183,
    # --- T ---
    "Tarleton State Texans": 2624,
    "TCU Horned Frogs": 2628,
    "Temple Owls": 218,
    "Tennessee Volunteers": 2633,
    "Tennessee State Tigers": 2634,
    "Tennessee Tech Golden Eagles": 2635,
    "Texas Longhorns": 251,
    "Texas A&M Aggies": 245,
    "Texas A&M-Commerce Lions": 2249,
    "Texas A&M-Corpus Christi Islanders": 357,
    "Texas Southern Tigers": 2640,
    "Texas State Bobcats": 326,
    "Texas Tech Red Raiders": 2641,
    "Texas-Arlington Mavericks": 250,
    "Texas-Rio Grande Valley Vaqueros": 292,
    "Texas-San Antonio Roadrunners": 2636,
    "The Citadel Bulldogs": 2643,
    "Toledo Rockets": 2649,
    "Towson Tigers": 119,
    "Troy Trojans": 2653,
    "Tulane Green Wave": 2655,
    "Tulsa Golden Hurricane": 2658,
    # --- U ---
    "UAB Blazers": 5,
    "UC-Davis Aggies": 302,
    "UC-Irvine Anteaters": 300,
    "UC-Riverside Highlanders": 27,
    "UC-San Diego Tritons": 28,
    "UC-Santa Barbara Gauchos": 2540,
    "UCF Knights": 2116,
    "UCLA Bruins": 26,
    "UIC Flames": 82,
    "UMass Minutemen": 113,
    "UMass-Lowell River Hawks": 2349,
    "UMBC Retrievers": 2378,
    "UNC-Asheville Bulldogs": 2427,
    "UNC-Greensboro Spartans": 2430,
    "UNC-Wilmington Seahawks": 350,
    "UNLV Rebels": 2439,
    "USC Trojans": 30,
    "UT-Martin Skyhawks": 2630,
    "Utah Utes": 254,
    "Utah State Aggies": 328,
    "Utah Tech Trailblazers": 3088,
    "Utah Valley Wolverines": 3084,
    "UTEP Miners": 2638,
    "UTSA Roadrunners": 2636,
    # --- V ---
    "Valparaiso Beacons": 2674,
    "Vanderbilt Commodores": 238,
    "VCU Rams": 2670,
    "Vermont Catamounts": 261,
    "Villanova Wildcats": 222,
    "Virginia Cavaliers": 258,
    "Virginia Tech Hokies": 259,
    "VMI Keydets": 2678,
    # --- W ---
    "Wagner Seahawks": 2681,
    "Wake Forest Demon Deacons": 154,
    "Washington Huskies": 264,
    "Washington State Cougars": 265,
    "Washington St Cougars": 265,
    "Weber State Wildcats": 2692,
    "West Georgia Wolves": 2698,
    "West Virginia Mountaineers": 277,
    "Western Carolina Catamounts": 2717,
    "Western Illinois Leathernecks": 2710,
    "Western Kentucky Hilltoppers": 98,
    "Western Michigan Broncos": 2711,
    "Wichita State Shockers": 2724,
    "William & Mary Tribe": 2729,
    "Winthrop Eagles": 2737,
    "Wisconsin Badgers": 275,
    "Wofford Terriers": 2747,
    "Wright State Raiders": 2750,
    "Wyoming Cowboys": 2751,
    # --- X ---
    "Xavier Musketeers": 2752,
    # --- Y ---
    "Yale Bulldogs": 43,
    "Youngstown State Penguins": 2754,
}


# ---------------------------------------------------------------------------
# Odds API team name -> short display abbreviation (max 6 chars)
#
# Standard college basketball abbreviations. For teams not in this dict,
# get_abbrev() falls back to the first word of the Odds API name.
# ---------------------------------------------------------------------------
ODDS_API_TO_ABBREV: dict[str, str] = {
    # --- A ---
    "Abilene Christian Wildcats": "ACU",
    "Air Force Falcons": "AF",
    "Akron Zips": "AKR",
    "Alabama Crimson Tide": "ALA",
    "Alabama A&M Bulldogs": "AAMU",
    "Alabama State Hornets": "ALST",
    "Albany Great Danes": "ALB",
    "Alcorn State Braves": "ALCS",
    "American Eagles": "AMER",
    "Appalachian State Mountaineers": "APP",
    "Arizona Wildcats": "ARIZ",
    "Arizona State Sun Devils": "ASU",
    "Arizona St Sun Devils": "ASU",
    "Arkansas Razorbacks": "ARK",
    "Arkansas State Red Wolves": "ARST",
    "Arkansas-Little Rock Trojans": "LR",
    "Arkansas-Pine Bluff Golden Lions": "ARPB",
    "Army Black Knights": "ARMY",
    "Auburn Tigers": "AUB",
    "Austin Peay Governors": "APSU",
    # --- B ---
    "Ball State Cardinals": "BALL",
    "Baylor Bears": "BAY",
    "Bellarmine Knights": "BELL",
    "Belmont Bruins": "BEL",
    "Bethune-Cookman Wildcats": "BCU",
    "Binghamton Bearcats": "BING",
    "Boise State Broncos": "BOIS",
    "Boston College Eagles": "BC",
    "Boston University Terriers": "BU",
    "Bowling Green Falcons": "BGSU",
    "Bradley Braves": "BRAD",
    "Brown Bears": "BRWN",
    "Bryant Bulldogs": "BRY",
    "Bucknell Bison": "BUCK",
    "Buffalo Bulls": "BUFF",
    "Butler Bulldogs": "BUT",
    "BYU Cougars": "BYU",
    # --- C ---
    "Cal Poly Mustangs": "CP",
    "Cal State-Bakersfield Roadrunners": "CSUB",
    "Cal State-Fullerton Titans": "CSUF",
    "Cal State-Northridge Matadors": "CSUN",
    "California Golden Bears": "CAL",
    "California Baptist Lancers": "CBU",
    "Campbell Fighting Camels": "CAMP",
    "Canisius Golden Griffins": "CAN",
    "Central Arkansas Bears": "UCA",
    "Central Connecticut State Blue Devils": "CCSU",
    "Central Florida Knights": "UCF",
    "Central Michigan Chippewas": "CMU",
    "Charleston Cougars": "COFC",
    "Charleston Southern Buccaneers": "CHSO",
    "Charlotte 49ers": "CLT",
    "Chattanooga Mocs": "UTC",
    "Chicago State Cougars": "CHST",
    "Cincinnati Bearcats": "CIN",
    "Clemson Tigers": "CLEM",
    "Cleveland State Vikings": "CLEV",
    "Coastal Carolina Chanticleers": "CCU",
    "Colgate Raiders": "COLG",
    "Colorado Buffaloes": "COLO",
    "Colorado State Rams": "CSU",
    "Columbia Lions": "CLMB",
    "Connecticut Huskies": "UCONN",
    "Coppin State Eagles": "COPP",
    "Cornell Big Red": "COR",
    "Creighton Bluejays": "CREI",
    # --- D ---
    "Dartmouth Big Green": "DART",
    "Davidson Wildcats": "DAV",
    "Dayton Flyers": "DAY",
    "DePaul Blue Demons": "DEP",
    "Delaware Fightin Blue Hens": "DEL",
    "Delaware State Hornets": "DSU",
    "Denver Pioneers": "DEN",
    "Detroit Mercy Titans": "DET",
    "Drake Bulldogs": "DRKE",
    "Drexel Dragons": "DREX",
    "Duke Blue Devils": "DUKE",
    "Duquesne Dukes": "DUQ",
    # --- E ---
    "East Carolina Pirates": "ECU",
    "East Texas A&M Lions": "ETAM",
    "Eastern Illinois Panthers": "EIU",
    "Eastern Kentucky Colonels": "EKU",
    "Eastern Michigan Eagles": "EMU",
    "Eastern Washington Eagles": "EWU",
    "Elon Phoenix": "ELON",
    "Evansville Purple Aces": "EVAN",
    # --- F ---
    "Fairfield Stags": "FAIR",
    "Fairleigh Dickinson Knights": "FDU",
    "FIU Panthers": "FIU",
    "Florida Gators": "FLA",
    "Florida A&M Rattlers": "FAMU",
    "Florida Atlantic Owls": "FAU",
    "Florida Gulf Coast Eagles": "FGCU",
    "Florida International Golden Panthers": "FIU",
    "Florida State Seminoles": "FSU",
    "Florida St Seminoles": "FSU",
    "Fordham Rams": "FOR",
    "Fresno State Bulldogs": "FRES",
    "Furman Paladins": "FUR",
    # --- G ---
    "Gardner-Webb Runnin Bulldogs": "GDWB",
    "George Mason Patriots": "GMU",
    "George Washington Colonials": "GW",
    "Georgetown Hoyas": "GTWN",
    "Georgia Bulldogs": "UGA",
    "Georgia Southern Eagles": "GASO",
    "Georgia State Panthers": "GAST",
    "Georgia Tech Yellow Jackets": "GT",
    "Gonzaga Bulldogs": "GONZ",
    "Grambling Tigers": "GRAM",
    "Grand Canyon Antelopes": "GCU",
    "Green Bay Phoenix": "GB",
    # --- H ---
    "Hampton Pirates": "HAMP",
    "Hartford Hawks": "HART",
    "Harvard Crimson": "HARV",
    "Hawaii Rainbow Warriors": "HAW",
    "Hawai'i Rainbow Warriors": "HAW",
    "High Point Panthers": "HPU",
    "Hofstra Pride": "HOF",
    "Holy Cross Crusaders": "HC",
    "Houston Cougars": "HOU",
    "Houston Christian Huskies": "HCU",
    "Howard Bison": "HOW",
    # --- I ---
    "Idaho Vandals": "IDHO",
    "Idaho State Bengals": "IDST",
    "Illinois Fighting Illini": "ILL",
    "Illinois State Redbirds": "ILST",
    "Illinois-Chicago Flames": "UIC",
    "Incarnate Word Cardinals": "UIW",
    "Indiana Hoosiers": "IND",
    "Indiana State Sycamores": "INST",
    "Indiana-Purdue-Indianapolis Jaguars": "IUPU",
    "Iona Gaels": "IONA",
    "Iowa Hawkeyes": "IOWA",
    "Iowa State Cyclones": "ISU",
    "IUPUI Jaguars": "IUPU",
    # --- J ---
    "Jackson State Tigers": "JKST",
    "Jacksonville Dolphins": "JAX",
    "Jacksonville State Gamecocks": "JVST",
    "James Madison Dukes": "JMU",
    # --- K ---
    "Kansas Jayhawks": "KU",
    "Kansas City Roos": "UMKC",
    "Kansas State Wildcats": "KSU",
    "Kennesaw State Owls": "KENN",
    "Kent State Golden Flashes": "KENT",
    "Kentucky Wildcats": "UK",
    # --- L ---
    "LIU Sharks": "LIU",
    "La Salle Explorers": "LAS",
    "Lafayette Leopards": "LAF",
    "Lamar Cardinals": "LAM",
    "Le Moyne Dolphins": "LEM",
    "Lehigh Mountain Hawks": "LEH",
    "Liberty Flames": "LIB",
    "Lindenwood Lions": "LIND",
    "Lipscomb Bisons": "LIP",
    "Little Rock Trojans": "LR",
    "Long Beach State Beach": "LBSU",
    "Long Island University Sharks": "LIU",
    "Louisiana Ragin Cajuns": "ULL",
    "Louisiana-Lafayette Ragin Cajuns": "ULL",
    "Louisiana-Monroe Warhawks": "ULM",
    "Louisiana Tech Bulldogs": "LATR",
    "Louisville Cardinals": "LOU",
    "Loyola Chicago Ramblers": "LOYC",
    "Loyola (IL) Ramblers": "LOYC",
    "Loyola (MD) Greyhounds": "LOYM",
    "Loyola Marymount Lions": "LMU",
    "LSU Tigers": "LSU",
    # --- M ---
    "Maine Black Bears": "ME",
    "Manhattan Jaspers": "MAN",
    "Marist Red Foxes": "MRST",
    "Marquette Golden Eagles": "MARQ",
    "Marshall Thundering Herd": "MRSH",
    "Maryland Terrapins": "MD",
    "Maryland-Eastern Shore Hawks": "UMES",
    "Massachusetts Minutemen": "MASS",
    "McNeese Cowboys": "MCN",
    "Memphis Tigers": "MEM",
    "Mercer Bears": "MER",
    "Merrimack Warriors": "MERR",
    "Miami Hurricanes": "MIA",
    "Miami (FL) Hurricanes": "MIA",
    "Miami (OH) RedHawks": "M-OH",
    "Michigan Wolverines": "MICH",
    "Michigan State Spartans": "MSU",
    "Middle Tennessee Blue Raiders": "MTSU",
    "Milwaukee Panthers": "MIL",
    "Minnesota Golden Gophers": "MINN",
    "Mississippi Rebels": "MISS",
    "Ole Miss Rebels": "MISS",
    "Mississippi State Bulldogs": "MSST",
    "Mississippi Valley State Delta Devils": "MVSU",
    "Missouri Tigers": "MIZ",
    "Missouri State Bears": "MOST",
    "Monmouth Hawks": "MON",
    "Montana Grizzlies": "MONT",
    "Montana State Bobcats": "MTST",
    "Morehead State Eagles": "MORE",
    "Morehead St Eagles": "MORE",
    "Morgan State Bears": "MORG",
    "Mount St. Mary's Mountaineers": "MSM",
    "Murray State Racers": "MURR",
    # --- N ---
    "Navy Midshipmen": "NAVY",
    "NC State Wolfpack": "NCST",
    "N.C. State Wolfpack": "NCST",
    "Nebraska Cornhuskers": "NEB",
    "Nebraska-Omaha Mavericks": "UNO",
    "Omaha Mavericks": "UNO",
    "Nevada Wolf Pack": "NEV",
    "New Hampshire Wildcats": "UNH",
    "New Mexico Lobos": "UNM",
    "New Mexico State Aggies": "NMSU",
    "New Orleans Privateers": "UNO",
    "Niagara Purple Eagles": "NIAG",
    "Nicholls State Colonels": "NICH",
    "NJIT Highlanders": "NJIT",
    "Norfolk State Spartans": "NORF",
    "North Alabama Lions": "UNA",
    "North Carolina Tar Heels": "UNC",
    "North Carolina A&T Aggies": "NCAT",
    "North Carolina Central Eagles": "NCCU",
    "North Carolina State Wolfpack": "NCST",
    "North Dakota Fighting Hawks": "UND",
    "North Dakota State Bison": "NDSU",
    "North Florida Ospreys": "UNF",
    "North Texas Mean Green": "UNT",
    "Northeastern Huskies": "NEU",
    "Northern Arizona Lumberjacks": "NAU",
    "Northern Colorado Bears": "UNCO",
    "Northern Illinois Huskies": "NIU",
    "Northern Iowa Panthers": "UNI",
    "Northern Kentucky Norse": "NKU",
    "Northwestern Wildcats": "NW",
    "Northwestern State Demons": "NWST",
    "Notre Dame Fighting Irish": "ND",
    # --- O ---
    "Oakland Golden Grizzlies": "OAK",
    "Ohio Bobcats": "OHIO",
    "Ohio State Buckeyes": "OSU",
    "Oklahoma Sooners": "OU",
    "Oklahoma State Cowboys": "OKST",
    "Oklahoma St Cowboys": "OKST",
    "Old Dominion Monarchs": "ODU",
    "Oral Roberts Golden Eagles": "ORU",
    "Oregon Ducks": "ORE",
    "Oregon State Beavers": "ORST",
    # --- P ---
    "Pacific Tigers": "PAC",
    "Penn Quakers": "PENN",
    "Penn State Nittany Lions": "PSU",
    "Pepperdine Waves": "PEPP",
    "Pittsburgh Panthers": "PITT",
    "Portland Pilots": "PORT",
    "Portland State Vikings": "PRST",
    "Prairie View A&M Panthers": "PVAM",
    "Presbyterian Blue Hose": "PRES",
    "Princeton Tigers": "PRIN",
    "Providence Friars": "PROV",
    "Purdue Boilermakers": "PUR",
    "Purdue Fort Wayne Mastodons": "PFW",
    # --- Q ---
    "Queens Royals": "QU",
    "Queens University Royals": "QU",
    "Quinnipiac Bobcats": "QUIN",
    # --- R ---
    "Radford Highlanders": "RAD",
    "Rhode Island Rams": "URI",
    "Rice Owls": "RICE",
    "Richmond Spiders": "RICH",
    "Rider Broncs": "RID",
    "Robert Morris Colonials": "RMU",
    "Rutgers Scarlet Knights": "RUT",
    # --- S ---
    "Sacramento State Hornets": "SAC",
    "Sacred Heart Pioneers": "SHU",
    "Saint Francis Red Flash": "SFU",
    "Saint Joseph's Hawks": "SJOE",
    "Saint Louis Billikens": "SLU",
    "Saint Mary's Gaels": "SMC",
    "Saint Peter's Peacocks": "SPU",
    "Sam Houston Bearkats": "SHSU",
    "Sam Houston State Bearkats": "SHSU",
    "Samford Bulldogs": "SAM",
    "San Diego Toreros": "USD",
    "San Diego State Aztecs": "SDSU",
    "San Diego St Aztecs": "SDSU",
    "San Francisco Dons": "USF",
    "San Jose State Spartans": "SJSU",
    "Santa Clara Broncos": "SCU",
    "Seattle Redhawks": "SEA",
    "Seton Hall Pirates": "HALL",
    "Siena Saints": "SIEN",
    "SIU-Edwardsville Cougars": "SIUE",
    "SMU Mustangs": "SMU",
    "South Alabama Jaguars": "USA",
    "South Carolina Gamecocks": "SC",
    "South Carolina State Bulldogs": "SCST",
    "South Carolina-Upstate Spartans": "UPST",
    "USC-Upstate Spartans": "UPST",
    "South Dakota Coyotes": "SDAK",
    "South Dakota State Jackrabbits": "SDST",
    "South Florida Bulls": "USF",
    "Southeast Missouri State Redhawks": "SEMO",
    "SE Missouri St Redhawks": "SEMO",
    "Southeastern Louisiana Lions": "SELA",
    "Southern Jaguars": "SOU",
    "Southern Illinois Salukis": "SIU",
    "Southern Miss Golden Eagles": "USM",
    "Southern Mississippi Golden Eagles": "USM",
    "Southern University Jaguars": "SOU",
    "Southern Utah Thunderbirds": "SUU",
    "St. Bonaventure Bonnies": "SBU",
    "St. John's Red Storm": "SJU",
    "St. Thomas Tommies": "STMN",
    "Stanford Cardinal": "STAN",
    "Stephen F. Austin Lumberjacks": "SFA",
    "Stetson Hatters": "STET",
    "Stonehill Skyhawks": "STHL",
    "Stony Brook Seawolves": "STON",
    "Syracuse Orange": "SYR",
    # --- T ---
    "Tarleton State Texans": "TARL",
    "TCU Horned Frogs": "TCU",
    "Temple Owls": "TEM",
    "Tennessee Volunteers": "TENN",
    "Tennessee State Tigers": "TNST",
    "Tennessee Tech Golden Eagles": "TNTH",
    "Texas Longhorns": "TEX",
    "Texas A&M Aggies": "TAMU",
    "Texas A&M-Commerce Lions": "TAMC",
    "Texas A&M-Corpus Christi Islanders": "AMCC",
    "Texas Southern Tigers": "TXSO",
    "Texas State Bobcats": "TXST",
    "Texas Tech Red Raiders": "TTU",
    "Texas-Arlington Mavericks": "UTA",
    "Texas-Rio Grande Valley Vaqueros": "UTRGV",
    "Texas-San Antonio Roadrunners": "UTSA",
    "The Citadel Bulldogs": "CIT",
    "Toledo Rockets": "TOL",
    "Towson Tigers": "TOW",
    "Troy Trojans": "TROY",
    "Tulane Green Wave": "TUL",
    "Tulsa Golden Hurricane": "TLSA",
    # --- U ---
    "UAB Blazers": "UAB",
    "UC-Davis Aggies": "UCD",
    "UC-Irvine Anteaters": "UCI",
    "UC-Riverside Highlanders": "UCR",
    "UC-San Diego Tritons": "UCSD",
    "UC-Santa Barbara Gauchos": "UCSB",
    "UCF Knights": "UCF",
    "UCLA Bruins": "UCLA",
    "UIC Flames": "UIC",
    "UMass Minutemen": "MASS",
    "UMass-Lowell River Hawks": "UML",
    "UMBC Retrievers": "UMBC",
    "UNC-Asheville Bulldogs": "UNCA",
    "UNC-Greensboro Spartans": "UNCG",
    "UNC-Wilmington Seahawks": "UNCW",
    "UNLV Rebels": "UNLV",
    "USC Trojans": "USC",
    "UT-Martin Skyhawks": "UTM",
    "Utah Utes": "UTAH",
    "Utah State Aggies": "USU",
    "Utah Tech Trailblazers": "UTU",
    "Utah Valley Wolverines": "UVU",
    "UTEP Miners": "UTEP",
    "UTSA Roadrunners": "UTSA",
    # --- V ---
    "Valparaiso Beacons": "VALP",
    "Vanderbilt Commodores": "VAN",
    "VCU Rams": "VCU",
    "Vermont Catamounts": "UVM",
    "Villanova Wildcats": "NOVA",
    "Virginia Cavaliers": "UVA",
    "Virginia Tech Hokies": "VT",
    "VMI Keydets": "VMI",
    # --- W ---
    "Wagner Seahawks": "WAG",
    "Wake Forest Demon Deacons": "WAKE",
    "Washington Huskies": "WASH",
    "Washington State Cougars": "WSU",
    "Washington St Cougars": "WSU",
    "Weber State Wildcats": "WEB",
    "West Georgia Wolves": "WGEO",
    "West Virginia Mountaineers": "WVU",
    "Western Carolina Catamounts": "WCU",
    "Western Illinois Leathernecks": "WIU",
    "Western Kentucky Hilltoppers": "WKU",
    "Western Michigan Broncos": "WMU",
    "Wichita State Shockers": "WICH",
    "William & Mary Tribe": "W&M",
    "Winthrop Eagles": "WIN",
    "Wisconsin Badgers": "WISC",
    "Wofford Terriers": "WOF",
    "Wright State Raiders": "WRST",
    "Wyoming Cowboys": "WYO",
    # --- X ---
    "Xavier Musketeers": "XAV",
    # --- Y ---
    "Yale Bulldogs": "YALE",
    "Youngstown State Penguins": "YSU",
}


# ---------------------------------------------------------------------------
# ESPN logo URL template
# ---------------------------------------------------------------------------
_ESPN_LOGO_URL = (
    "https://a.espncdn.com/combiner/i?"
    "img=/i/teamlogos/ncaa/500/{id}.png&w=40&h=40"
)


def _fuzzy_lookup(name: str, mapping: dict) -> str | None:
    """Try common Odds API name variants (St↔State, etc.)."""
    # Try expanding "St" -> "State"
    if " St " in name:
        expanded = name.replace(" St ", " State ")
        if expanded in mapping:
            return mapping[expanded]
    # Try contracting "State" -> "St"
    if " State " in name:
        contracted = name.replace(" State ", " St ")
        if contracted in mapping:
            return mapping[contracted]
    # Try "SE " -> "Southeast "
    if name.startswith("SE "):
        expanded = "Southeast " + name[3:]
        if expanded in mapping:
            return mapping[expanded]
    return None


def get_logo_url(odds_api_name: str) -> str:
    """Return the ESPN CDN logo URL for a team, or empty string if unknown.

    Args:
        odds_api_name: Team name as returned by The Odds API
                       (e.g. "Alabama Crimson Tide").

    Returns:
        Full ESPN CDN logo URL, or "" if the team is not mapped.
    """
    espn_id = ODDS_API_TO_ESPN_ID.get(odds_api_name)
    if espn_id is None:
        espn_id = _fuzzy_lookup(odds_api_name, ODDS_API_TO_ESPN_ID)
    if espn_id is None:
        return ""
    return _ESPN_LOGO_URL.format(id=espn_id)


def get_abbrev(odds_api_name: str) -> str:
    """Return a short abbreviation for display.

    Args:
        odds_api_name: Team name as returned by The Odds API.

    Returns:
        Short abbreviation (max 6 chars), or the first word of the
        team name if not explicitly mapped.
    """
    abbrev = ODDS_API_TO_ABBREV.get(odds_api_name)
    if abbrev is not None:
        return abbrev
    # Try fuzzy matching
    abbrev = _fuzzy_lookup(odds_api_name, ODDS_API_TO_ABBREV)
    if abbrev is not None:
        return abbrev
    # Fallback: first word of team name
    parts = odds_api_name.split()
    return parts[0] if parts else odds_api_name
